// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(SyscscContext))]
    partial class SyscscContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entity.Pasajero", b =>
                {
                    b.Property<int>("Identificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Identificacion");

                    b.ToTable("Pasajeros");
                });

            modelBuilder.Entity("Entity.Tiquete", b =>
                {
                    b.Property<int>("TiqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<int?>("PasajeroIdentificacion")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .HasColumnType("text");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("TiqueteId");

                    b.HasIndex("PasajeroIdentificacion");

                    b.ToTable("Tiquetes");
                });

            modelBuilder.Entity("Entity.Tiquete", b =>
                {
                    b.HasOne("Entity.Pasajero", null)
                        .WithMany("Tiquetes")
                        .HasForeignKey("PasajeroIdentificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
